import React from 'react';
import Giscus from '@giscus/react';

interface CommentsProps {
  theme?: 'light' | 'dark';
}

const Comments: React.FC<CommentsProps> = () => {
  // Check system preference or app state for theme if needed, 
  // but for now we can infer from document class or pass as prop
  const isDark = document.documentElement.classList.contains('dark');

  return (
    <div className="w-full mt-12 pt-12 border-t border-border/50">
      <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
        <span>💬</span>
        <span>Discussions</span>
      </h3>
      
      {/* 
        IMPORTANT: You must replace these values with your own from https://giscus.app 
        1. Enable GitHub Discussions on your public repo.
        2. Install Giscus App on that repo.
        3. Copy the attributes generated by giscus.app below.
      */}
      <div className="min-h-[200px]">
        <Giscus
          id="comments"
          repo="giscus/giscus-component" // REPLACE THIS with your username/repo
          repoId="MDEwOlJlcG9zaXRvcnkzNTE5NTgwNTM=" // REPLACE THIS with your repo ID
          category="General" // REPLACE THIS
          categoryId="DIC_kwDOFP_hZc4B-hVS" // REPLACE THIS
          mapping="pathname"
          term="Welcome to Lumina!"
          reactionsEnabled="1"
          emitMetadata="0"
          inputPosition="top"
          theme={isDark ? 'transparent_dark' : 'light'}
          lang="en"
          loading="lazy"
        />
      </div>
      <p className="text-xs text-muted-foreground mt-4 text-center">
        Powered by GitHub Discussions. Requires GitHub login to comment.
      </p>
    </div>
  );
};

export default Comments;